create table public.measurements (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  measurements json not null,
  constraint measurements_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public."measurements" ENABLE ROW LEVEL SECURITY;
