create table public.data (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  value numeric not null,
  constraint data_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public."data" ENABLE ROW LEVEL SECURITY;
